# Generated by Django 5.2.13 on 2026-05-04 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_cuentaabierta_venta_detalleventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.CharField(max_length=255)),
                ('valor_nuevo', models.CharField(max_length=255)),
                ('motivo', models.TextField(blank=True)),
                ('usuario_corrector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='gestion.venta')),
            ],
        ),
    ]
