# Generated by Django 5.2.14 on 2026-07-24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def inicializar_saldo_ventas(apps, schema_editor):
    Venta = apps.get_model('gestion', 'Venta')
    ventas_cuenta_abierta = Venta.objects.filter(cuenta_abierta__isnull=False)
    ventas_cuenta_abierta.update(saldo=models.F('total'))
    Venta.objects.filter(cuenta_abierta__isnull=True).update(saldo=0)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_producto_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PagoCuentaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta_abierta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='gestion.cuentaabierta')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cuentas_abiertas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImputacionPagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputaciones', to='gestion.pagocuentaabierta')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones_pago', to='gestion.venta')),
            ],
            options={
                'ordering': ['venta__fecha', 'venta_id'],
            },
        ),
        migrations.RunPython(inicializar_saldo_ventas, migrations.RunPython.noop),
    ]
