# Generated by Django 5.2.14 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_venta_saldo_pagos_cuenta_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaabierta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
