# Generated by Django 5.2.14 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_cuentaabierta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='salida_motivo',
            field=models.CharField(choices=[('manual', 'Manual'), ('expirada', 'Expirada'), ('sin_cierre', 'Sin cierre previo')], default='manual', max_length=20),
        ),
    ]
